### PR TITLE
Map locales si_LK, sq_AL

### PR DESCRIPTION
**Pull request by mimckenna**
Map new languages to their respective regions
* Albanian sq to sq_AL (Albania)
* Sinhala si to si_LK Sri (Lanka)

### CODE REVIEW

**Comment by mstuart** [comment]
@gregjopa @mnicpt @bluepnume curious, can you `npm run build` this project after a fresh install? I get a weird babel error now. Tried clearing my npm cache and node_modules too.

image

**Comment by mnicpt** [comment]
Looking

**Comment by mstuart** [comment]
Figured it out. ty @mnicpt !

**Comment by mstuart** [comment]
`+ @paypal/sdk-constants@1.0.88`

**Pull request merged**
