### PR TITLE
chore: Added Constant for PUI Funding Source

### PR DESCRIPTION
**Pull request by RatnadeepSimhadri**
This is required for PUI Legal Text Integration through. `@paypal/legal-components` 
https://github.com/paypal/paypal-legal-components

### CODE REVIEW

**Comment by TNuzzi** [comment]
Looks like there may be some linting issues.

**Comment by RatnadeepSimhadri** [comment]
> Looks like there may be some linting issues.

Let me validate . Thats weird. The `pre-commit` hook didn't catch anything

**Comment by westeezy** [comment]
> > Looks like there may be some linting issues.
> 
> Let me validate . Thats weird. The `pre-commit` hook didn't catch anything

There is no pre-commit hook in this repo unfortunately

**Comment by RatnadeepSimhadri** [comment]
> > > Looks like there may be some linting issues.
> > 
> > 
> > Let me validate . Thats weird. The `pre-commit` hook didn't catch anything
> 
> There is no pre-commit hook in this repo unfortunately

No Issues i Fixed it and added a commit. Would it be ok if I can create PR with pre-commit hook

**Review by westeezy — APPROVED** [review]

**Pull request merged**
